### ISSUE TITLE
Serializing `FixedOffsetTimeZone` produces unexepcted result

### ISSUE THREAD

**Issue by kevincianfarini** [Kotlin/kotlinx-datetime#222]
When serializing the constant `TimeZone.UTC`, which is a `FixedOffsetTimeZone`, I was seeing the value `"Z"`. Comparing this against the tzdb, I don't believe this to be the right value. I believe the correctly encoded value should be one of: 

* `Etc/Zulu`
* `Etc/UTC`
* `Zulu`
* `UTC`

I am unsure if other instances of `FixedOffsetTimeZone` experience the same problem. I'm happy to help dig in if more info is needed.

**Comment by kevincianfarini** [comment]
This was causing unexpected backend issues as our API contract requires tzdb entries. Switching to `TimeZone.of("UTC")` solves the problem.

**Comment by ilya-g** [comment]
It is expected that the string representation of a `FixedOffsetTimeZone` doesn't produce a value that can be found in a time zone database: usually, it's something like `+-hh:mm` and the case of `+00:00` is represented specially as `Z`.

Though, it should always be possible to obtain a `TimeZone` value from such a string, either with `kotlinx.datetime`, or with `java.time`. Could you tell more about your backend requirement, why it is not the case there?

**Comment by kevincianfarini** [comment]
> Though, it should always be possible to obtain a TimeZone value from such a string, either with kotlinx.datetime, or with java.time.

Can you clarify this bit? The issue was manifesting when passing in a hardcoded value of `TimeZone.UTC`. As far as I was aware, I _was_ using a TimeZone value. 

> Could you tell more about your backend requirement, why it is not the case there?

Our backend service expects a tzdb entry to allow for dynamic handling of daylight savings time. `Z` is not a tzdb entry, and also does not aid in the handling of daylight savings time. 

I realize that `UTC` does not undergo daylight savings time, and therefore it is a moot point. _However_, it's strange to me that serializing `TimeZone.UTC` and `TimeZone.of("UTC")` results in different values. 

I would expect any timezone serializer to produce the tzdb name, and a separate `Offset` serializer to produce either `+-hh:mm` or `Z`. It seems that `FixedOffsetTimeZone` conflates those two concerns.

**Comment by ilya-g** [comment]
>> Though, it should always be possible to obtain a TimeZone value from such a string, either with kotlinx.datetime, or with java.time.

> Can you clarify this bit? The issue was manifesting when passing in a hardcoded value of TimeZone.UTC.

In **kotlinx.datetime**: `TimeZone.of("Z")` returns a `FixedOffsetTimeZone` (which is an inheritor of `TimeZone`) same as `TimeZone.UTC`
In **java.time**: `ZoneId.of("Z")` returns a `ZoneOffset` same as `ZoneOffset.UTC` (`ZoneOffset` is an inheritor of `ZoneId`)

So from this point of view, the value `Z` could be used to identify an instance of `TimeZone`/`ZoneId`.

**Comment by kevincianfarini** [comment]
Does a serializer exist which will try to serialize with a tzdb entry, or fail? Being explicit about that would have helped solve my issue.

**Comment by ilya-g** [comment]
No, since a `FixedOffsetTimeZone` is a `TimeZone`, a serializer that can serialize a `TimeZone` also accepts instances of `FixedOffsetTimeZone`.

What could help in your situation, is separating a tzdb-rules-based time zone into a distinct inheritor of `TimeZone` and exposing it publicly. This way you could require using this type of time zones in your API and the type system would help you to rule out using `FixedOffsetTimeZone` during the compilation.

We can consider this change to the `TimeZone` hierarchy.

**Comment by kevincianfarini** [comment]
> In java.time: ZoneId.of("Z") returns a ZoneOffset same as ZoneOffset.UTC (ZoneOffset is an inheritor of ZoneId)
>
> So from this point of view, the value Z could be used to identify an instance of TimeZone/ZoneId.

Java time also doesn't have a `UtcOffset` class which kotlinx does. Looking at the docs 

```kt
/**
 * An offset from UTC.
 *
 * Examples of these values:
 * - `Z`, an offset of zero;
 * - `+05`, plus five hours;
 * - `-02`, minus two hours;
 * - `+03:30`, plus three hours and thirty minutes;
 * - `+01:23:45`, plus one hour, 23 minutes, and 45 seconds.
 */
@Serializable(with = UtcOffsetSerializer::class)
public expect class UtcOffset {
```

It looks like the `UtcOffset` serializer does exactly what you claim the `FixedOffsetTimeZone` serializer does as well. I am a bit confused about the duplication of functionality here. Given this functionality exists in kotlinx.datetime, I find it very confusing that _some_ timezones also express this behavior.

**Comment by ilya-g** [comment]
`java.time` has the class `ZoneOffset` which is an inheritor of `ZoneId` and combines the functionality of expressing an offset from UTC and using it as a time zone. We decided to split these aspects into separate classes. 
It's true that `FixedOffsetTimeZone` and `UtcOffset` have the same representation when serialized to string, but it doesn't mean that their functionality is duplicated.

**Comment by kevincianfarini** [comment]
@ilya-g I guess I have more broad question. What function does `FixedOffsetTimeZone` serve that `UtcOffset` does not also serve?

**Comment by ilya-g** [comment]
- `FixedOffsetTimeZone` can be used as a time zone, while `UtcOffset` can't. 
- `UtcOffset` is designated to express an offset from UTC (for example when querying `TimeZone.offsetAt(Instant)` offset value), while `FixedOffsetTimeZone` represents a time zone having a fixed UTC offset specified by its `offset` value.

**Comment by kevincianfarini** [comment]
As a side note, thank you for time and helping me understand the problem at hand @ilya-g 😄

**Comment by dkhalanskyjb** [comment]
> Yes, but what end function does this serve?

I see the difference between them as the difference between numbers (`5`, `-10`) and functions that return numbers (`{ _ -> 5 }`, `{ _ -> 10 }`). Another analogy is the difference between a clock reading (the position of the hour and minute hands) and a clock that is stuck. Is a clock that is stuck forever *literally* just the time that it shows?

A time zone is a function that maps the actual time to the `UtcOffset` that is used in that location at that moment, and a fixed-offset time zone is, when seen like this, a constant function.

> What end functions (that I'm potentially unaware of) does a `FixedOffsetTimeZone` facilitate that a `UtcOffset` cannot?

`FixedOffsetTimeZone`, as you saw, also stores the name of the timezone. For example, GMT and UTC are both timezones that are fixed-offset and always have the `UtcOffset` value of zero, but they even have different Wikipedia pages: https://en.wikipedia.org/wiki/Universal_Time https://en.wikipedia.org/wiki/Greenwich_Mean_Time Time zones are used not only for computation but also for communication. If someone says something is in the GMT timezone, maybe the *do* want to highlight that it's not the UTC timezone. Who knows.

**Comment by kevincianfarini** [comment]
> Time zones are used not only for computation but also for communication. If someone says something is in the GMT timezone, maybe the do want to highlight that it's not the UTC timezone. Who knows.

If this is the case, why are timezones serialized to their UTC offset value versus their name? At that point communication is no different than passing around an unnamed `UtcOffset`.

**Comment by dkhalanskyjb** [comment]
Huh? `TimeZone.of("GMT").toString()` returns `"GMT"` for me, and if you're talking about actual serialization, it's also using the ID, not the offset: https://github.com/Kotlin/kotlinx-datetime/blob/master/core/common/src/serializers/TimeZoneSerializers.kt#L51 Could you provide an example of a place where we forget the provided name?

**Comment by kevincianfarini** [comment]
Like mentioned above, the constant `TimeZone.UTC` uses the `FixedOffsetTimeZoneSerializer` which serializes to `Z`. This can be mitigated by using `TimeZone.of("UTC")` which feels really unintuitive.

**Comment by kevincianfarini** [comment]
Hi, I'd like to revive this thread to further my understanding. I still don't understand why `FixedOffsetTimeZone` is something that we really need. To summarize: 

1. The issue arose because `TimeZone.UTC != TimeZone.of("UTC")`. Both produce a `FixedOffsetTimeZone`, but one has a valid tzdb id and the other doesn't. 
    * See: #326 and #474. 
2. A `FixedOffsetTimeZone` can be created from a `UtcOffset` and its id will be reflect an [ISO-8601 UTC offset](https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC). 
    * <details>
        <summary>Example</summary>
   
        ```kt
        TimeZone.of("UTC").id // UTC
        TimeZone.UTC.id // Z
        UtcOffset(hours = 2).asTimeZone().id // +02:00
        ```
      </details>
3. A `FixedOffsetTimeZone` created from a `UtcOffset` does not have a meaningful identifier and does not correspond to a tzdb entry. 
4. All `Instant <-> LocalDate[Time]` conversions that use a `FixedOffsetTimeZone` could also be achieved using a `UtcOffset` instance. 
    * Not all conversions are exposed for `UtcOffset`, but some are. Namely [`LocalDateTime.toInstant(UtcOffset)`](https://github.com/Kotlin/kotlinx-datetime/blob/latest-release/core/common/src/TimeZone.kt#L255)


With this understanding I think it's logical to conclude that a `FixedOffsetTimeZone` is often just a wrapper around `UtcOffset`. One of the arguments in favor of fixed time zones was that it can be used throughout kotlinx-datetime as a TimeZone, but that argument feels hollow since some functions already accept a UtcOffset. If we exposed those functions, like `Instant.toLocalDateTime(UtcOffset)`, then that argument would be moot. 

Furthermore, I feel that the proposal in #326 to have two separate timezone implementations is perhaps overly complicated and misleading to library consumers. Most users of this library will expect that a TimeZone corresponds to a tzdb entry, and FixedOffsetTimeZone failing to do so has caused a fair amount of confusion. Like mentioned above, a TimeZone is a mapping between a current instant and its UtcOffset. The _concept_ of fixed offset time zones could be trivially implemented like so, but in my opinion those rules should be and implementation detail of TimeZone that are dictated by the tzdb entry: 

```kt
// A simplified example. 
public object UTCTimeZone {
  override val id: String get() = "UTC"
  override fun offsetAt(instant: Instant): UtcOffset = UtcOffset(0)
}
```

A counterproposal to #326 could be: 

* Every conversion between Instant and LocalDateTime should accept both a TimeZone and a UtcOffset. This would facilitate variable offsets and fixed offsets. 
* `FixedOffsetTimeZone` is deprecated and removed in favor of the functions which operate on UtcOffset. 
* `TimeZone` is altered so that it always represents a valid TZDB entry. 
* The useful constant `TimeZone.UTC` would encode the proper TZDB identifier and UtcOffset rules and would not require querying for a TZDB entry as shown above. 

This proposal breaks down if there's any circumstances where a `FixedOffsetTimeZone` serves more use cases than a `UtcOffset`, but I'm failing to find any such case. In such a future state a TimeZone instance _might_ have a fixed UtcOffset, but that'd be an implementation detail and time zone would not guarantee that functionality. A TimeZone would, however, guarantee to encode a TZDB id, which is not currently the case.

**Comment by dkhalanskyjb** [comment]
The issue is that the default (and incorrect) approach when working with time zones is to use UTC offsets. You can see this everywhere, including this issue tracker, where some users don't see the difference between time zones and the UTC offsets and use the terms interchangeably. Usually, time zones are what you actually want, whereas UTC offsets are a low-level, technical thing, but this is often forgotten.

With that in mind, imagine that you want to create some procedure that works with both UTC offsets and time zones; you don't know if the client code has access to a timezone identifier or only a UTC offset from some legacy database. For example, say we need to implement `Clock.todayIn(TimeZone)` + `Clock.todayIn(UtcOffset)`. Only the first one of these two is provided in our library, which encourages our users to obtain a proper timezone identifier, but if that fails, to convert the UTC offset into a time zone. Alternatively, we could have provided `Clock.todayIn(UtcOffset)` as a separate overload and disallow converting a `UtcOffset` into a time zone, but:
1. This would mean everyone everywhere writing functions accepting a `TimeZone` would have to create a duplicate function accepting a `UtcOffset`, for the use case of interacting with external systems that don't expose timezone identifiers.
2. This wouldn't discourage using `UtcOffset`. We don't want `Clock.System.todayIn(UtcOffset(hours = 2))` to be just as convenient as `Clock.System.todayIn(TimeZone.of("Europe/Berlin"))`, we want the extra effort that goes into writing `Clock.System.todayIn(UtcOffset(hours = 2).asTimeZone())` to indicate that no, `+02:00` is not a time zone, there's a better way.

**Comment by ilya-g** [comment]
The behavior of `TimeZone.UTC != TimeZone.of("UTC")` originally recreated the similar behavior of java.time time zones:
```
    println(ZoneOffset.UTC)    // Z
    println(ZoneId.of("UTC"))  // UTC
    println(ZoneOffset.UTC == ZoneId.of("UTC")) // false
    println(ZoneOffset.UTC == ZoneId.of("Z"))   // true
```
https://pl.kotl.in/UBujjuZnE (compare to kotlinx-datetime: https://pl.kotl.in/mJ0jPPVvP)

The difference is that we placed the constant `UTC` in the base time zone class instead of its fixed-offset inheritor.
This can indeed be somewhat confusing, so we potentially could make `TimeZone.UTC == TimeZone.of("UTC")` and in most cases it won't change the observed behavior except in formatting/serialization. 
The risks, however, are that the difference between that and java.time would also become a source of confusion. We can introduce a separate constant for `TimeZone.of("Z")`, but it would be hard to explain the difference from the `UTC` constant and when one should use which.

@kevincianfarini I also don't get what do you mean by that `TimeZone.UTC` doesn't have a valid tzdb indentifier? Both `TimeZone.of` in kotlinx-datetime and `ZoneId.of` in java.time accept `Z` as a time zone identifier.

**Comment by kevincianfarini** [comment]
> I also don't get what do you mean by that TimeZone.UTC doesn't have a valid tzdb indentifier? Both TimeZone.of in kotlinx-datetime and ZoneId.of in java.time accept Z as a time zone identifier.

This was mentioned a little further up the thread, but we discussed that `Z` is the ISO-8601 UTC offset and not tzdb identifier, which should be one of: 

- Etc/Zulu
- Etc/UTC
- Zulu
- UTC

My backend is written in Python and is unable to interpret `Z` as a valid tzdb identifier, for example. 

> The difference is that we placed the constant UTC in the base time zone class instead of its fixed-offset inheritor.
This can indeed be somewhat confusing, so we potentially could make TimeZone.UTC == TimeZone.of("UTC") and in most cases it won't change the observed behavior except in formatting/serialization.
The risks, however, are that the difference between that and java.time would also become a source of confusion. We can introduce a separate constant for TimeZone.of("Z"), but it would be hard to explain the difference from the UTC constant and when one should use which.

I think this approach will resolve #474 but it fails to resolve this issue. The argument that I'm trying to make is that a `TimeZone` should _always_ correspond to an entry in tzdb, and `FixedOffsetTimeZone` doesn't meet that requirement by design. Extending that argument a bit further necessitates that `FixedOffsetTimeZone` as its currently implemented _isn't always a time zone_ and could potentially be better served by a different abstraction altogether, like `UtcOffset`. 

If the intent of `UtcOffset.asTimeZone()` is indeed to add friction to convenience operations like `Clock.todayIn(TimeZone)` as mentioned above, that is not made apparent to library consumers in a highly visible way (like with `@RequiresOptIn` annotation). Instead, it's documented on the function as a pitfall. 

> Pitfall: UTC offsets are static values and do not change with time. If the logic requires that the offset changes with time, for example, to account for daylight-saving-time transitions, use [TimeZone.of](https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/-time-zone/-companion/of.html) with an IANA time zone name to obtain a time zone that can handle changes in the offset.

This is not something I would catch in code review if I was not extremely familiar with this Github issue in the first place. As such, I think it would be really great if, before a 1.0.0 release, the maintainers of kotlinx-datetime considered if they're solving the problem of missing tzdb entries at the wrong layer of abstraction. It's an uncommon operation for very specific scenarios and we've bolted on functionality to `TimeZone` that is confusing in the "normal" case. 

I think that deviating from `java.time` norms here would help add clarity to these operations and would further nudge library consumers in the right direction. Providing operations on `UtcOffset` behind an opt-in annotation means this library could still support uncommon use cases, but in a way that's more clear and easier to call out in code review.

**Comment by dkhalanskyjb** [comment]
> if you're able to rephrase it that would be helpful.

Sure. Here are the constraints were are facing:

* In some codebases/services/formats, only UTC offsets are available, instead of proper time zones, so it must be possible to use UTC offsets everywhere one could use a time zone.
* We don't want to duplicate every function that accepts `TimeZone` by one that accepts `UtcOffset`, because that would encourage using `UtcOffset` even when the time zone is available.
* We don't want to demand that third-party libraries written on top of `kotlinx-datetime` add such overloads, because it's extra work, and it's easy to forget to do that.

> I'd like to counter that and state that this indirection has caused confusion for the normal use case where API consumers are trying to use a valid tzdb timezone, but are surprised to find TimeZone.UTC isn't one, for example.

Ok, that's one example. If we change the timezone identifier of `TimeZone.UTC`, do you see any other issues with `FixedOffsetTimeZone`?

> Instead, do you think it makes more sense to offer overloads that accept a `UtcOffset` and mark them with a `@RequiresOptIn` annotation?

We could do that, but suggesting third-party libraries using `kotlinx.datetime` to do that is unrealistic, I don't think we will be able to coordinate this solution over the Kotlin ecosystem.

> direct consumers of this library who are operating without valid tzdb entries to write their own extension functions

Why make life intentionally difficult for those that are forced to use UTC offsets?

> I imagine this use case is very rare, and when people encounter it, they'll more likely look towards loading a custom tzdb rules set versus operating on UtcOffset directly.

It's unfortunately anything but rare. Also, if you receive `{"date":"2024-12-31T20:16:55","timeZone":"+02:00"}` from some web service, custom tzdb rules won't save you.

**Comment by kevincianfarini** [comment]
> Ok, that's one example. If we change the timezone identifier of TimeZone.UTC, do you see any other issues with FixedOffsetTimeZone?

This is of course a hypothetical example, but since you mentioned this JSON `{"date":"2024-12-31T20:16:55","timeZone":"+02:00"}` I think it's reasonable to claim two things: 

1. If I were to deserialize `timeZone` as a `kotlinx.datetime.TimeZone` and then try to send that to my backend service which expects TimeZone instances to correspond to an entry in tzdb, this would fail. In this case the best thing we could do is check if each time zone we're sending to our backend instance is a `FixedOffsetTimeZone` and then just throw an exception if it is. Essentially, the presence of `FixedOffsetTimeZone` completely stops me from treating timezones as opaque identifiers that I can send to other services which don't behave similarly to `kotlinx.datetime` or `java.time`. This feels leaky and requires that I know if an external service additionally supports ISO-8601 offsets as timezones despite it only documenting tzdb ID support. 
2. A separate solution to this assuming that `timeZone` in this example is actually always a UTC offset would be to either concatenate these two strings to form a valid ISO-8601 qualified encoding which `Instant.parse` will adjust for, or manually do the conversion yourself with a UtcOffset. In this case the `timeZone` parameter could simply be named more accurately. 

However, if `timeZone` can optionally be an ISO-8601 endoded UTC offset _xor_ an IANA time zone then it seems like the tradeoff we're forced to make is between: 

1. Supporting services which encode UTC offsets as timezones (which is arguably incorrect based on [tzdb's definition of timezone](https://en.wikipedia.org/wiki/Tz_database#Data_structure)), and
2. Facilitating the ability to treat timezones as opaque identifiers which correspond to some rules that allow conversion between UTC time and local time. 

If kotlinx-datetime maintainers choose to favor (1) then at the very least we should be clear that `kotlinx.datetime.TimeZone` does not strictly adhere to the tzdb's definition of timezone. 

Overall, it seems like the maintainers _currently_ want to imply people using UtcOffsets should practice extra care since it's probably not the best way to achieve an end goal. As a result of this implementation, people using `TimeZone` in the normal case that we're trying to nudge people towards also have to practice extra care, and that seems like a leaky implementation to me. 

> We could do that, but suggesting third-party libraries using kotlinx.datetime to do that is unrealistic, I don't think we will be able to coordinate this solution over the Kotlin ecosystem.

Why is this unrealistic? Currently the risk of using UtcOffset is hidden behind `FixedOffsetTimeZone` so it feels a bit like we're dancing around the issue -- _using a fixed offset for your operations likely isn't correct and while doing so you should practice extra care_. This seems particularly bad if, like me prior to reporting this issue, people are naively treating `TimeZone` as an opaque identifier when deseralizing a value from a network call. They could be opting themselves into dangerous behavior that the kotlinx-datetime tries to nudge people away from without even knowing!

**Comment by dkhalanskyjb** [comment]
> If I were to deserialize timeZone as a kotlinx.datetime.TimeZone and then try to send that to my backend service which expects TimeZone instances to correspond to an entry in tzdb, this would fail

That's true. If your backend has to exchange data with some other code, this means you have to agree on a common format. If your backend promises to parse what `kotlinx-datetime` has in `TimeZone`, it needs to be able to parse the strings listed in https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/-time-zone/-companion/of.html, or you can't make that promise. There is no way to work around the need to establish a shared format.

> In this case the timeZone parameter could simply be named more accurately.

My point was not the name, but the fact that some systems have to work with UTC offsets instead of timezone identitiers and can not realistically do anything about it.

> This feels leaky and requires that I know if an external service additionally supports ISO-8601 offsets as timezones despite it only documenting tzdb ID support.

That's incorrect, we do document the set of IDs we accept.

> Supporting services which encode UTC offsets as timezones (which is arguably incorrect based on [tzdb's definition of timezone](https://en.wikipedia.org/wiki/Tz_database#Data_structure))

The tzdb itself includes time zones like `Etc/GMT+11`, which don't fit that definition, so the definition is incorrect. What we and Java are doing is a generalization of such time zones.

> treat timezones as opaque identifiers which correspond to some rules that allow conversion between UTC time and local time

You can treat UTC offsets as such by forgetting they are UTC offsets. That's what `utcOffset.asTimeZone()` does.

> people using `TimeZone` in the normal case that we're trying to nudge people towards also have to practice extra care

With https://github.com/Kotlin/kotlinx-datetime/issues/326, you'd be able to avoid this issue completely by only using `RegionTimeZone`. If there is no `TimeZone` in your program but only `RegionTimeZone`, all identifiers you'd have are IANA tzdb ones.

> Why is this unrealistic?

It's needless code duplication (the logic is the same), needless duplication of documentation (the behavior is the same), it's something every library with `TimeZone`-accepting functions will have to do eventually (because the use case of not having timezone identifiers is not going anywhere), it's needless friction for `UtcOffset` users who will have to constantly guess if the function they are about to call already has the correct overload, or they'll have to create an issue to add it. Basically, it's a minor but widespread pain for both library writers and users.

**Comment by kevincianfarini** [comment]
> That's incorrect, we do document the set of IDs we accept.

Sorry, let me clarify. I meant the documentation of the backend service, not kotlinx-datetime. 

Regardless, I've tried to make my case and it seems like it wasn't good enough. Thanks for engaging, and whatever direction we go, I'm sure it will reduce the confusion of `TimeZone.UTC != TimeZone.of("UTC")`.
